"""vasp-gen — light INCAR template generator (CLI symmetry with omx-gen).

Writes INCAR only. Does not create POTCAR/KPOINTS or submit jobs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PKG_DIR = Path(__file__).resolve().parent
TEMPLATES_PATH = PKG_DIR / "schemas" / "templates.json"


def _load_templates() -> dict[str, Any]:
    raw = json.loads(TEMPLATES_PATH.read_text(encoding="utf-8"))
    if isinstance(raw, dict) and "data" in raw:
        data = raw["data"]
    else:
        data = raw
    if not isinstance(data, dict):
        raise ValueError("templates.json must be an object of template records")
    return data


def _format_incar_value(val: Any) -> str:
    if isinstance(val, bool):
        return ".TRUE." if val else ".FALSE."
    if isinstance(val, float):
        # compact but stable
        if val == 0:
            return "0"
        s = f"{val:.6g}"
        return s
    if isinstance(val, int):
        return str(val)
    return str(val)


def render_incar(
    tags: dict[str, Any],
    *,
    comments: list[str] | None = None,
) -> str:
    lines: list[str] = []
    if comments:
        for c in comments:
            lines.append(f"# {c}")
        lines.append("")
    for key, val in tags.items():
        lines.append(f"{key} = {_format_incar_value(val)}")
    lines.append("")
    return "\n".join(lines)


def apply_overrides(
    tags: dict[str, Any],
    sets: list[str] | None = None,
    spin: int | None = None,
    cutoff: float | None = None,
) -> dict[str, Any]:
    out = dict(tags)
    if spin is not None:
        out["ISPIN"] = int(spin)
    if cutoff is not None:
        out["ENCUT"] = float(cutoff)
    for item in sets or []:
        if "=" not in item:
            raise ValueError(f"override must be KEY=VALUE, got {item!r}")
        k, v = item.split("=", 1)
        k = k.strip()
        v = v.strip()
        # try numeric/bool
        low = v.lower()
        if low in (".true.", "true", "t"):
            out[k] = True
        elif low in (".false.", "false", "f"):
            out[k] = False
        else:
            try:
                if "." in v or "e" in low:
                    out[k] = float(v)
                else:
                    out[k] = int(v)
            except ValueError:
                out[k] = v
    return out


def structure_comment(structure_path: str | None) -> list[str]:
    if not structure_path:
        return ["generated by vasp-gen (INCAR only)"]
    p = Path(structure_path)
    comments = [f"generated by vasp-gen from {p.name}"]
    if not p.is_file():
        comments.append(f"WARNING: structure not found: {structure_path}")
        return comments
    try:
        from ase.io import read  # type: ignore

        atoms = read(str(p))
        comments.append(f"formula={atoms.get_chemical_formula()} natoms={len(atoms)}")
    except Exception as e:
        comments.append(f"structure note: could not parse ({e})")
    return comments


def generate(
    template: str,
    *,
    structure: str | None = None,
    sets: list[str] | None = None,
    spin: int | None = None,
    cutoff: float | None = None,
    dry_run: bool = False,
    output: str | None = None,
    json_output: bool = False,
    verbose: bool = False,
) -> dict[str, Any]:
    templates = _load_templates()
    if template not in templates:
        avail = ", ".join(sorted(templates))
        raise KeyError(f"Unknown template {template!r}. Available: {avail}")
    rec = templates[template]
    tags = dict(rec.get("tags") or {})
    tags = apply_overrides(tags, sets=sets, spin=spin, cutoff=cutoff)
    comments = structure_comment(structure)
    comments.insert(0, f"template={template}: {rec.get('description', '')}")
    text = render_incar(tags, comments=comments)
    if verbose:
        print(f"[INFO] template={template} tags={len(tags)}", file=sys.stderr)
    if json_output:
        payload = {
            "template": template,
            "description": rec.get("description", ""),
            "tags": tags,
            "incar": text,
        }
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return payload
    if dry_run or not output or output == "-":
        sys.stdout.write(text)
        return {"template": template, "tags": tags, "output": "-"}
    out_path = Path(output)
    out_path.write_text(text, encoding="utf-8")
    if verbose:
        print(f"[INFO] wrote {out_path}", file=sys.stderr)
    return {"template": template, "tags": tags, "output": str(out_path)}


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="vasp-gen",
        description="Generate a light VASP INCAR from templates (no POTCAR/KPOINTS)",
    )
    parser.add_argument(
        "structure",
        nargs="?",
        default=None,
        help="Optional structure file (POSCAR/CIF/XYZ) — used for comments only",
    )
    parser.add_argument(
        "-t", "--template", default="scf",
        help="Template id (default: scf)",
    )
    parser.add_argument("-o", "--output", default=None, help="Output INCAR path")
    parser.add_argument(
        "-s", "--set", action="append", default=[], dest="sets",
        help="Override KEY=VALUE (repeatable)",
    )
    parser.add_argument("--spin", type=int, choices=[1, 2], default=None, help="ISPIN")
    parser.add_argument("--cutoff", type=float, default=None, help="ENCUT in eV")
    parser.add_argument("-d", "--dry-run", action="store_true", help="Print to stdout")
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("-j", "--json", action="store_true", dest="json_output")
    parser.add_argument(
        "--list-templates", action="store_true",
        help="List available templates and exit",
    )
    args = parser.parse_args(argv)

    try:
        templates = _load_templates()
    except Exception as e:
        print(json.dumps({
            "error": f"Failed to load templates: {e}",
            "suggestion": f"Check {TEMPLATES_PATH}",
        }))
        return 1

    if args.list_templates:
        if args.json_output:
            print(json.dumps({
                "templates": [
                    {"id": k, "description": v.get("description", "")}
                    for k, v in sorted(templates.items())
                ]
            }, indent=2, ensure_ascii=False))
        else:
            print("Available templates:")
            for k, v in sorted(templates.items()):
                print(f"  {k:12s}  {v.get('description', '')}")
        return 0

    try:
        generate(
            args.template,
            structure=args.structure,
            sets=args.sets,
            spin=args.spin,
            cutoff=args.cutoff,
            dry_run=args.dry_run or args.output is None,
            output=args.output,
            json_output=args.json_output,
            verbose=args.verbose,
        )
    except KeyError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": "Use --list-templates to see ids",
        }))
        return 1
    except ValueError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": "Pass -s KEY=VALUE (e.g. -s ENCUT=520)",
        }))
        return 1
    except Exception as e:
        print(json.dumps({
            "error": f"vasp-gen failed: {e}",
            "suggestion": "Check template name and overrides",
        }))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(cli())
