"""vasp-gen — light VASP input generator (CLI symmetry with omx-gen).

Default: INCAR from templates.
Optional (pymatgen): KPOINTS, POSCAR copy, POTCAR (requires local PSP dir).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

PKG_DIR = Path(__file__).resolve().parent
TEMPLATES_PATH = PKG_DIR / "schemas" / "templates.json"


def _load_templates() -> dict[str, Any]:
    raw = json.loads(TEMPLATES_PATH.read_text(encoding="utf-8"))
    if isinstance(raw, dict) and "data" in raw:
        data = raw["data"]
    else:
        data = raw
    if not isinstance(data, dict):
        raise ValueError("templates.json must be an object of template records")
    return data


def _format_incar_value(val: Any) -> str:
    if isinstance(val, bool):
        return ".TRUE." if val else ".FALSE."
    if isinstance(val, float):
        if val == 0:
            return "0"
        return f"{val:.6g}"
    if isinstance(val, int):
        return str(val)
    return str(val)


def render_incar(
    tags: dict[str, Any],
    *,
    comments: list[str] | None = None,
) -> str:
    lines: list[str] = []
    if comments:
        for c in comments:
            lines.append(f"# {c}")
        lines.append("")
    for key, val in tags.items():
        lines.append(f"{key} = {_format_incar_value(val)}")
    lines.append("")
    return "\n".join(lines)


def apply_overrides(
    tags: dict[str, Any],
    sets: list[str] | None = None,
    spin: int | None = None,
    cutoff: float | None = None,
) -> dict[str, Any]:
    out = dict(tags)
    if spin is not None:
        out["ISPIN"] = int(spin)
    if cutoff is not None:
        out["ENCUT"] = float(cutoff)
    for item in sets or []:
        if "=" not in item:
            raise ValueError(f"override must be KEY=VALUE, got {item!r}")
        k, v = item.split("=", 1)
        k = k.strip()
        v = v.strip()
        low = v.lower()
        if low in (".true.", "true", "t"):
            out[k] = True
        elif low in (".false.", "false", "f"):
            out[k] = False
        else:
            try:
                if "." in v or "e" in low:
                    out[k] = float(v)
                else:
                    out[k] = int(v)
            except ValueError:
                out[k] = v
    return out


def structure_comment(structure_path: str | None) -> list[str]:
    if not structure_path:
        return ["generated by vasp-gen"]
    p = Path(structure_path)
    comments = [f"generated by vasp-gen from {p.name}"]
    if not p.is_file():
        comments.append(f"WARNING: structure not found: {structure_path}")
        return comments
    try:
        struct = load_structure(str(p))
        formula = struct.composition.reduced_formula
        comments.append(f"formula={formula} natoms={len(struct)}")
    except Exception as e:
        comments.append(f"structure note: could not parse ({e})")
    return comments


def load_structure(path: str):
    """Load a pymatgen Structure from common structure files."""
    from pymatgen.core import Structure

    p = Path(path)
    if not p.is_file():
        raise FileNotFoundError(f"structure not found: {path}")
    return Structure.from_file(str(p))


def kpoints_from_structure(
    structure,
    *,
    kspacing: float | None = None,
    kdensity: float | None = None,
    gamma: bool = True,
):
    """Build pymatgen Kpoints.

    *kspacing* (1/Å): mesh n_i = max(1, ceil(|b_i| / kspacing)).
    *kdensity*: pymatgen ``automatic_density`` / ``automatic_gamma_density``.
    Default if neither set: kdensity=100.
    """
    from pymatgen.io.vasp.inputs import Kpoints
    import numpy as np

    if kspacing is not None and kdensity is not None:
        raise ValueError("pass only one of --kspacing or --kdensity")

    if kspacing is not None:
        if kspacing <= 0:
            raise ValueError("--kspacing must be positive")
        # reciprocal lattice lengths in 1/Å
        b = structure.lattice.reciprocal_lattice.abc
        mesh = [max(1, int(np.ceil(bi / kspacing))) for bi in b]
        if gamma:
            return Kpoints.gamma_automatic(kpts=mesh)
        return Kpoints.monkhorst_automatic(kpts=mesh)

    dens = 100.0 if kdensity is None else float(kdensity)
    if dens <= 0:
        raise ValueError("--kdensity must be positive")
    if gamma:
        return Kpoints.automatic_gamma_density(structure, dens)
    return Kpoints.automatic_density(structure, dens)


def potcar_from_structure(
    structure,
    *,
    functional: str = "PBE",
):
    """Build Potcar from structure element symbols. Needs PMG_VASP_PSP_DIR."""
    from pymatgen.io.vasp.inputs import Potcar

    psp = os.environ.get("PMG_VASP_PSP_DIR") or os.environ.get("VASP_PSP_DIR")
    if not psp or not Path(psp).is_dir():
        raise EnvironmentError(
            "POTCAR generation requires a local VASP pseudopotential directory. "
            "Set PMG_VASP_PSP_DIR (or VASP_PSP_DIR) to your PSP root "
            "(e.g. .../POT_GGA_PAW_PBE). Pseudopotentials are NOT redistributed."
        )
    symbols = [str(el) for el in structure.composition.elements]
    return Potcar(symbols, functional=functional)


def _resolve_output_paths(
    output: str | None,
    dry_run: bool,
    want_suite: bool,
) -> dict[str, Path | None]:
    """Map logical artifacts to paths.

    - dry-run: no paths (stdout INCAR only; suite files described in JSON)
    - output is directory (exists or ends with /): write suite into it
    - output is file path: INCAR there; siblings for KPOINTS/POTCAR/POSCAR
    - output None: dry-run style for INCAR
    """
    if dry_run or not output or output == "-":
        return {"incar": None, "dir": None}

    out = Path(output)
    is_dir = output.endswith("/") or output.endswith(os.sep) or (
        out.exists() and out.is_dir()
    ) or want_suite and out.suffix == ""
    if is_dir:
        return {
            "dir": out,
            "incar": out / "INCAR",
            "kpoints": out / "KPOINTS",
            "potcar": out / "POTCAR",
            "poscar": out / "POSCAR",
        }
    return {
        "dir": out.parent if str(out.parent) != "" else Path("."),
        "incar": out,
        "kpoints": out.parent / "KPOINTS",
        "potcar": out.parent / "POTCAR",
        "poscar": out.parent / "POSCAR",
    }


def generate(
    template: str,
    *,
    structure: str | None = None,
    sets: list[str] | None = None,
    spin: int | None = None,
    cutoff: float | None = None,
    dry_run: bool = False,
    output: str | None = None,
    json_output: bool = False,
    verbose: bool = False,
    kspacing: float | None = None,
    kdensity: float | None = None,
    write_kpoints: bool = False,
    gamma: bool = True,
    write_potcar: bool = False,
    potcar_functional: str = "PBE",
    write_poscar: bool = False,
) -> dict[str, Any]:
    templates = _load_templates()
    if template not in templates:
        avail = ", ".join(sorted(templates))
        raise KeyError(f"Unknown template {template!r}. Available: {avail}")
    rec = templates[template]
    tags = dict(rec.get("tags") or {})
    tags = apply_overrides(tags, sets=sets, spin=spin, cutoff=cutoff)
    comments = structure_comment(structure)
    comments.insert(0, f"template={template}: {rec.get('description', '')}")
    text = render_incar(tags, comments=comments)

    want_kpoints = write_kpoints or kspacing is not None or kdensity is not None
    want_suite = want_kpoints or write_potcar or write_poscar
    paths = _resolve_output_paths(output, dry_run=dry_run, want_suite=want_suite)

    struct = None
    if structure:
        struct = load_structure(structure)
    elif want_kpoints or write_potcar or write_poscar:
        raise ValueError(
            "structure file required for KPOINTS/POTCAR/POSCAR generation"
        )

    kpts_obj = None
    kpts_str = None
    if want_kpoints:
        assert struct is not None
        kpts_obj = kpoints_from_structure(
            struct, kspacing=kspacing, kdensity=kdensity, gamma=gamma,
        )
        kpts_str = str(kpts_obj)

    potcar_obj = None
    if write_potcar:
        assert struct is not None
        potcar_obj = potcar_from_structure(
            struct, functional=potcar_functional,
        )

    written: dict[str, str] = {}

    if verbose:
        print(
            f"[INFO] template={template} tags={len(tags)} "
            f"kpoints={want_kpoints} potcar={write_potcar}",
            file=sys.stderr,
        )

    # dry-run / stdout: INCAR to stdout; other artifacts only in JSON
    if dry_run or paths["incar"] is None:
        if not json_output:
            sys.stdout.write(text)
        payload = {
            "template": template,
            "description": rec.get("description", ""),
            "tags": tags,
            "incar": text,
            "written": written,
        }
        if kpts_str is not None:
            payload["kpoints"] = kpts_str
        if write_potcar:
            payload["potcar"] = (
                f"(would write POTCAR for "
                f"{[str(e) for e in struct.composition.elements]})"
            )
        if json_output:
            print(json.dumps(payload, indent=2, ensure_ascii=False))
        return payload

    # write files
    incar_path = Path(paths["incar"])  # type: ignore[arg-type]
    incar_path.parent.mkdir(parents=True, exist_ok=True)
    incar_path.write_text(text, encoding="utf-8")
    written["INCAR"] = str(incar_path)

    if kpts_obj is not None:
        kp = Path(paths["kpoints"])  # type: ignore[arg-type]
        kpts_obj.write_file(str(kp))
        written["KPOINTS"] = str(kp)

    if potcar_obj is not None:
        pp = Path(paths["potcar"])  # type: ignore[arg-type]
        potcar_obj.write_file(str(pp))
        written["POTCAR"] = str(pp)

    if write_poscar and struct is not None:
        from pymatgen.io.vasp.inputs import Poscar

        pp = Path(paths["poscar"])  # type: ignore[arg-type]
        Poscar(struct).write_file(str(pp))
        written["POSCAR"] = str(pp)

    if verbose:
        for k, v in written.items():
            print(f"[INFO] wrote {k}: {v}", file=sys.stderr)

    payload = {
        "template": template,
        "description": rec.get("description", ""),
        "tags": tags,
        "written": written,
        "output": str(incar_path),
    }
    if json_output:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    return payload


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="vasp-gen",
        description=(
            "Generate VASP INCAR from templates; optional KPOINTS/POTCAR/POSCAR "
            "via pymatgen (POTCAR needs PMG_VASP_PSP_DIR)"
        ),
    )
    parser.add_argument(
        "structure",
        nargs="?",
        default=None,
        help="Structure file (POSCAR/CIF/XYZ); required for KPOINTS/POTCAR/POSCAR",
    )
    parser.add_argument(
        "-t", "--template", default="scf",
        help="Template id (default: scf)",
    )
    parser.add_argument(
        "-o", "--output", default=None,
        help="INCAR path or directory for a multi-file suite",
    )
    parser.add_argument(
        "-s", "--set", action="append", default=[], dest="sets",
        help="Override KEY=VALUE (repeatable)",
    )
    parser.add_argument("--spin", type=int, choices=[1, 2], default=None, help="ISPIN")
    parser.add_argument("--cutoff", type=float, default=None, help="ENCUT in eV")
    parser.add_argument(
        "--kspacing", type=float, default=None,
        help="Write KPOINTS with mesh from reciprocal spacing (1/Å)",
    )
    parser.add_argument(
        "--kdensity", type=float, default=None,
        help="Write KPOINTS via pymatgen automatic_(gamma_)density",
    )
    parser.add_argument(
        "--kpoints", action="store_true", dest="write_kpoints",
        help="Write KPOINTS (default density 100 if neither --kspacing nor --kdensity)",
    )
    parser.add_argument(
        "--monkhorst", action="store_true",
        help="Use Monkhorst-Pack instead of Gamma-centered mesh",
    )
    parser.add_argument(
        "--potcar", action="store_true", dest="write_potcar",
        help="Write POTCAR (requires PMG_VASP_PSP_DIR and structure)",
    )
    parser.add_argument(
        "--potcar-functional", default="PBE",
        help="POTCAR functional family (default: PBE)",
    )
    parser.add_argument(
        "--poscar", action="store_true", dest="write_poscar",
        help="Also write POSCAR from the structure",
    )
    parser.add_argument("-d", "--dry-run", action="store_true", help="Print INCAR to stdout")
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("-j", "--json", action="store_true", dest="json_output")
    parser.add_argument(
        "--list-templates", action="store_true",
        help="List available templates and exit",
    )
    args = parser.parse_args(argv)

    try:
        templates = _load_templates()
    except Exception as e:
        print(json.dumps({
            "error": f"Failed to load templates: {e}",
            "suggestion": f"Check {TEMPLATES_PATH}",
        }))
        return 1

    if args.list_templates:
        if args.json_output:
            print(json.dumps({
                "templates": [
                    {"id": k, "description": v.get("description", "")}
                    for k, v in sorted(templates.items())
                ]
            }, indent=2, ensure_ascii=False))
        else:
            print("Available templates:")
            for k, v in sorted(templates.items()):
                print(f"  {k:12s}  {v.get('description', '')}")
        return 0

    # default dry-run when no -o and not writing suite files only
    dry = args.dry_run or (
        args.output is None
        and not (args.write_kpoints or args.kspacing or args.kdensity
                 or args.write_potcar or args.write_poscar)
    )

    try:
        generate(
            args.template,
            structure=args.structure,
            sets=args.sets,
            spin=args.spin,
            cutoff=args.cutoff,
            dry_run=dry,
            output=args.output,
            json_output=args.json_output,
            verbose=args.verbose,
            kspacing=args.kspacing,
            kdensity=args.kdensity,
            write_kpoints=args.write_kpoints,
            gamma=not args.monkhorst,
            write_potcar=args.write_potcar,
            potcar_functional=args.potcar_functional,
            write_poscar=args.write_poscar,
        )
    except KeyError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": "Use --list-templates to see ids",
        }))
        return 1
    except FileNotFoundError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": "Pass a valid structure path (POSCAR/CIF/XYZ)",
        }))
        return 1
    except EnvironmentError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": (
                "pmg config --add PMG_VASP_PSP_DIR /path/to/POT_GGA_PAW_PBE "
                "or export PMG_VASP_PSP_DIR; never commit POTCAR"
            ),
        }))
        return 1
    except ValueError as e:
        print(json.dumps({
            "error": str(e),
            "suggestion": "Check --kspacing/--kdensity and -s KEY=VALUE flags",
        }))
        return 1
    except ImportError as e:
        print(json.dumps({
            "error": f"pymatgen required for this feature: {e}",
            "suggestion": 'pip install -e ".[omx]" or pip install pymatgen',
        }))
        return 1
    except Exception as e:
        print(json.dumps({
            "error": f"vasp-gen failed: {e}",
            "suggestion": "Check template, structure, and pymatgen install",
        }))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(cli())
