"""Ground-truth probes against mature VASP tooling.

Primary GT: **pymatgen** (Structure / Kpoints / Incar).
Secondary: **pydefect** input-package shape (optional import).
vaspkit: documented conventions only (no Python API required).

See ``docs/superpowers/specs/2026-07-14-semantic-roundtrip-design.md`` §8.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# Files vasp-gen may write (suite mode)
VASP_GEN_SUITE_FILES = frozenset({"INCAR", "KPOINTS", "POSCAR", "POTCAR"})

# Minimal static VASP run (our generator scope)
VASP_SCF_MINIMAL = frozenset({"INCAR", "KPOINTS", "POSCAR", "POTCAR"})

# Typical pydefect / defect workflow extras (not generated by dft-tools)
# Documented shape — not an exhaustive pydefect inventory.
PYDEFECT_DEFECT_EXTRA = frozenset({
    "supercell_info.json",
    "defect_entry.json",
    "prior_info.json",
    "defect_structure_info.json",
    "correction.json",
    "band_edge_states.json",
})


def pymatgen_available() -> bool:
    try:
        import pymatgen  # noqa: F401
        from pymatgen.io.vasp.inputs import Kpoints, Incar  # noqa: F401
        return True
    except Exception:
        return False


def pydefect_available() -> bool:
    try:
        import pydefect  # noqa: F401
        return True
    except Exception:
        return False


def kpoints_mesh_from_kspacing(structure, kspacing: float, *, gamma: bool = True):
    """Reference mesh using the same policy as ``vasp_query.generator``."""
    from vasp_query.generator import kpoints_from_structure

    return kpoints_from_structure(
        structure, kspacing=kspacing, kdensity=None, gamma=gamma,
    )


def probe_kpoints_roundtrip_file(
    structure_path: Path | str,
    kpoints_path: Path | str,
    *,
    kspacing: float,
    gamma: bool = True,
) -> dict[str, Any]:
    """Compare on-disk KPOINTS to pymatgen rebuild from structure + kspacing.

    Returns a report dict with ``ok`` and mesh fields.
    """
    from pymatgen.core import Structure
    from pymatgen.io.vasp.inputs import Kpoints

    structure = Structure.from_file(str(structure_path))
    expected = kpoints_mesh_from_kspacing(structure, kspacing, gamma=gamma)
    actual = Kpoints.from_file(str(kpoints_path))

    exp_style = str(expected.style) if hasattr(expected, "style") else None
    act_style = str(actual.style) if hasattr(actual, "style") else None
    exp_kpts = [tuple(x) for x in expected.kpts]
    act_kpts = [tuple(x) for x in actual.kpts]

    ok = exp_kpts == act_kpts and (
        exp_style is None or act_style is None or exp_style == act_style
        or ("Gamma" in str(exp_style) and "Gamma" in str(act_style))
        or ("Monkhorst" in str(exp_style) and "Monkhorst" in str(act_style))
    )
    return {
        "ok": ok,
        "expected_kpts": exp_kpts,
        "actual_kpts": act_kpts,
        "expected_style": exp_style,
        "actual_style": act_style,
        "kspacing": kspacing,
        "gamma": gamma,
    }


def probe_incar_pymatgen_accepts(incar_dict: dict[str, Any]) -> dict[str, Any]:
    """Ensure pymatgen ``Incar`` accepts our decoded/generated tag dict."""
    from pymatgen.io.vasp.inputs import Incar

    # pymatgen prefers native types; copy
    data = {str(k).upper(): v for k, v in incar_dict.items()}
    # Drop free-text SYSTEM-like if needed — keep all for now
    incar = Incar(data)
    # Round-trip through as_dict
    back = incar.as_dict()
    # strip @module metadata if present
    clean = {k: v for k, v in back.items() if not str(k).startswith("@")}
    return {
        "ok": True,
        "n_tags": len(incar),
        "tags": sorted(str(k) for k in incar.keys()),
        "as_dict_keys": sorted(clean.keys()),
    }


def probe_pydefect_shape() -> dict[str, Any]:
    """Report pydefect availability and documented input-package shape.

    Does **not** run a defect workflow — only boundary documentation for GT.
    """
    available = pydefect_available()
    version = None
    if available:
        import pydefect
        version = getattr(pydefect, "__version__", None)
    return {
        "available": available,
        "version": version,
        "vasp_gen_suite": sorted(VASP_GEN_SUITE_FILES),
        "scf_minimal": sorted(VASP_SCF_MINIMAL),
        "pydefect_extra_json_artifacts": sorted(PYDEFECT_DEFECT_EXTRA),
        "note": (
            "dft-tools generates SCF-level VASP inputs only; "
            "pydefect owns defect supercell/charge-correction JSON artifacts."
        ),
    }
